### ISSUE TITLE
Non-interactive mode should not print progress bar

### ISSUE THREAD

**Issue by psolymos** [kvnkuang/pbmcapply#1]
@kvnkuang : I was using the package in a **knitr** document and the output had the progress bar:

```
## 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |=                                                                |   1%
  |                                                                       
  |==                                                               |   2%
```

Not copying here the whole output, but you can guess the rest. I would suggest printing the progress bar only when `interactive()`. At least this is what I did in **pbapply**.

**Comment by kvnkuang** [comment]
Thanks for reporting, I will fix this ASAP.

**Comment by kvnkuang** [comment]
Detection of interactive mode added with commit 14c7db7.
