### ISSUE TITLE
must have 'max' > 'min'

### ISSUE THREAD

**Issue by iSevenDays** [kvnkuang/pbmcapply#11]
I had 3 operations. They were sequential. First two operations finished successfully, but second operation(probably) had an error in the end, please see the error below.
Third operation as I see even wasn't started.

[1] "Started processing"
  |======================================================================================================| 100%
  |======================================================================================================| 100%
Fehler in txtProgressBar(0, length, style = mc.style) : 
  must have 'max' > 'min'

**Comment by kvnkuang** [comment]
Thanks for reaching out. Could you please check whether your vector for the third operation is empty? It needs to have at least one element.

**Comment by iSevenDays** [comment]
@kvnkuang ,yes thank you, I found that the third vector was empty

**Comment by kvnkuang** [comment]
Great! Glad it helped. 

This issue has been addressed in the commit #6 by providing a better error message when the input vector is empty. It will ship with the next release.

If you want to stay tuned, please feel free to star this project :)
