### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by maRce10** [kvnkuang/pbmcapply#15]
Thanks for the cool package. I have been waiting for this functionality for quite a while. 

I included this package as a dependency to my package ("warbleR"). However, I just realized that pbmcapply can't be installed on windows OS. This would largely limit the range of users. It might be better if it can be installed on windows OS but return and error if more than 1 core is attempted to be used as in the parallel package ("'mc.cores' > 1 is not supported on Windows"). 

thanks

**Comment by kvnkuang** [comment]
Hi maRce10,

Thanks for reaching out. I am glad to know that my package helps! Yes, I do plan to make `pbmcapply`available for Windows users. I will adopt the temporal fix as you suggested, and will eventually implement the `mc.cores` functionality on Windows myself.

Regards,
Kevin

**Comment by kvnkuang** [comment]
This issue has been addressed with 99fc925 - now online in version 1.2.2.

**Comment by maRce10** [comment]
thanks! So now it can be installed on windows?

**Comment by kvnkuang** [comment]
Yes, for now parallelization (mc.core > 1) does not work on Windows. It will return with an error if mc.core is set to >1. 

Meanwhile, I am still working on porting `mc*apply` to Windows platform.

**Comment by maRce10** [comment]
Awesome. thanks a lot Kvnkuang! please let me know when porting on windows is available.

**Comment by maRce10** [comment]
I just tried on windows and was able to install it. But it does freezes R when trying to run pbmclapply. see the inscreen shots
![screenshot from 2017-05-30 09-59-04](https://cloud.githubusercontent.com/assets/13245502/26592733/e679cda8-451e-11e7-9185-fe4b9567e528.png)
![screenshot from 2017-05-30 09-56-26](https://cloud.githubusercontent.com/assets/13245502/26592734/e67d4c44-451e-11e7-9954-548052ae98ba.png)

**Comment by kvnkuang** [comment]
Thanks a lot for reporting. I am looking into this now.

**Comment by kvnkuang** [comment]
A quick update on this issue.

After spending some time on this issue, I figured out that the crash is caused by the R's implementation of `fifo` on Windows. I am still trying to make this work.

**Comment by maRce10** [comment]
Hello, Any luck with this?

**Comment by kvnkuang** [comment]
Hi maRce10, sorry I haven't got much time to work on this issue...
I think I will write some code to bypass the bug for now and when I have time, I will then work on a legit fix when I have time.

Thanks,
Kevin

**Comment by maRce10** [comment]
Hi Kevin

no worries. The main problem I had at this time is that it cannot be installed on windows OS, so in its current form I cannot keep it as a dependency. You could allow Windows users to install it but simply return an error if more than 1 core is attempted to be used as in the parallel package ("'mc.cores' > 1 is not supported on Windows"), or a warning message that is running sequentially.

thanks!

**Comment by kvnkuang** [comment]
Hi maRce10,

Thanks again for your advice! I have pushed a temp fix to the repo under the dev branch. If you don't mind, could you please help me test it on a Windows machine?

You can install the update by executing the following commands in R:
```
library(devtools)
install_github("kvnkuang/pbmcapply", ref = "dev")
```

Regards,
Kevin

**Comment by maRce10** [comment]
Hi Kevin

I tested it and worked fine. Thanks a lot!



![image](https://user-images.githubusercontent.com/13245502/29027572-3a72b468-7b4f-11e7-93e7-906f3b1e1856.png)

**Comment by kvnkuang** [comment]
Thanks a lot for testing! I have submitted the update to CRAN. Hopefully, it will get accepted within a few days and you will be able to include it in your package dependency.
