### ISSUE TITLE
Reset plan() on exit

### ISSUE THREAD

**Issue by HenrikBengtsson** [kvnkuang/pbmcapply#2]
I just like to suggest that you undo your changes to `plan()` when you exit your functions, e.g.
```r
pbmclapply <- function(X, FUN, ..., mc.style = 3, mc.cores =getOption("mc.cores", 2L)) {
  oplan <- plan("list")
  on.exit(plan(oplan))

  plan(multiprocess)
```
Otherwise there's a risk that calling this function will break other functions / scripts relying on futures called afterwards.

**Comment by kvnkuang** [comment]
Thanks for suggesting. I will take a look into it. 
Also, thanks for making `future` for R :)

**Comment by kvnkuang** [comment]
Reset plan() on exit added with commit 14c7db7.
