### ISSUE TITLE
The link to the blog post with comparison does not work

### ISSUE THREAD

**Issue by krassowski** [kvnkuang/pbmcapply#20]
@kvnkuang, thank you for this package it seems to be a nice extension to parallel.

Would it be possible to recover the post with comparison and/or upload it to GitHub so it remains available regardless of the blog status?

That's how "https://kevinkuang.net/tracking-progress-in-r-ad97998c359f" looks in my browser:
![screenshot from 2017-11-30 23-49-17](https://user-images.githubusercontent.com/5832902/33462772-1daf4640-d629-11e7-9bf0-715661a9ebb9.png)
(It also shows Error 502: bad gateway)

**Comment by krassowski** [comment]
I've found a working copy on R-bloggers: [Tracking progress in R](https://www.r-bloggers.com/tracking-progress-in-r/) (if there is someone else interested too).

**Comment by kvnkuang** [comment]
It should be fixed now. Thanks for letting me know about it!
