### ISSUE TITLE
size of globals too big for future

### ISSUE THREAD

**Issue by hsmith9002** [kvnkuang/pbmcapply#21]
Hello Kevin,

I want to use your pbmclapply() function to run linear models for an analysis I am working on. I have a dataset (cpg.p) that has 850K columns. Each one of these is a probe set that I am using as a predictor in the linear models. This means I will be running 850K linear models. I run this code where cpg.p is the dataset with 850K columns, and f is a simple function I wrote that fits the models and extracts the coefficients and p-values:
`rslts.p <- do.call("rbind", pbmclapply(cpg.p, FUN = f, mc.cores =getOption("mc.cores", 20L)))`
I am getting this error:
`Error in getGlobalsAndPackages(expr, envir = envir, tweak = tweakExpression,  : 
  The total size of the 3 globals that need to be exported for the future expression (‘do.call(what = FUN, args = args)’) is 696.56 MiB. This exceeds the maximum allowed size of 500.00 MiB (option 'future.globals.maxSize'). There are three globals: ‘args’ (696.55 MiB of class ‘list’), ‘FUN’ (5.55 KiB of class ‘function’) and ‘progressFifo’ (552 bytes of class ‘numeric’).`
I am thinking this has something to do with the fact the cpg.p is too big for the future? If I run the same code with a smaller dataset (e.g. 250K) it runs beautifully. I can easily split up the dataset, run the code, and recombine, but I was wondering if there is a workaround when working with large datasets like mine?

Thank you
Harry

**Comment by kvnkuang** [comment]
Hey Harry,

Thanks for letting me know. I will look into this and push an update to fix it.

Regards,
Kevin

**Comment by kvnkuang** [comment]
Hey Harry.

I pushed a fix to the dev branch. Could you please test to see if it works?

You can install `pbmcapply` from the dev branch using the following R commands:
```
library(devtools)
install_github("kvnkuang/pbmcapply", ref = "dev")
```

Thanks,
Kevin

**Comment by hsmith9002** [comment]
Yes, it works great now. Thank you!

Harry

**Comment by kvnkuang** [comment]
Thanks for the feedback. I have pushed an update to CRAN. Hopefully, it will be accepted in days.

Kevin
