### ISSUE TITLE
Some values in result list are just NULL

### ISSUE THREAD

**Issue by martin-ueding** [kvnkuang/pbmcapply#23]
I have a strange issue since I have upgraded to R 3.5.0 and installed the latest CRAN version of this package. The resulting list from a `pbmclapply` call *sometimes* contains some `NULL` elements. Replacing the same with `lapply` gives the desired result of no `NULL` elements. Also with `mclapply` it seems to work, though I am not sure whether this was just luck or this is some sort of a race condition.

Could `pbmclapply` behave differently in the result compared to `mclapply` and `apply`?

**Comment by kvnkuang** [comment]
Hi Martin,

Is it possible to provide me a piece of code that would trigger this problem? And on what platform?

Thanks,
Kevin

**Comment by martin-ueding** [comment]
I have tried it during the past two weeks and I also found the problem with `parallel::mclapply`. The thing seems to happen most of the time (if not always) when using the `boot` packages which works with the random number generator. Perhaps that leads to a race condition.

If I manage to come up with a reproducible example, I will come back to this issue, otherwise I would consider it just invalid.

**Comment by deto** [comment]
Not sure if this was ever figured out, but I was having the same issue today.

Oddly, it only occurred when running my script in non-interactive mode - which it looks like just passes the computation to 'mclapply'.  However, if I just substituted mclapply in *my* code, then it worked just fine (no NULLs).

This all occurred using version 1.3.0 of the package and was fixed when I upgraded to 1.3.1.  No idea why the changes between those versions would have caused/fixed this, but I just wanted to mention it and the details around this in case it shows up for other people.

**Comment by kvnkuang** [comment]
Thanks for keeping us updated.

I am not sure how it was solved either since I didn't have code that will reproduce this bug. Maybe it was fixed because I slightly changed how non-vector objects are handled. Or it could be that the maintainers of the `parallel` package fixed it recently.

Anyway, I am glad it's fixed 😄
