### ISSUE TITLE
Width calculation problem if ETA has hours (or longer)

### ISSUE THREAD

**Issue by scottkosty** [kvnkuang/pbmcapply#25]
Consider the following example:

```
library(pbmcapply)

lazySqrt <- function(num) {
  # Sleep randomly between 0 to 0.5 second
  Sys.sleep(runif(1, 0, 0.5))
  return(sqrt(num))
}


# Get the sqrt of 1-3 in parallel
result <- pbmclapply(seq.int(10^7), lazySqrt, mc.cores = 2)
```

When I run the above code, because the ETA is hours, I think that a longer line is output by `pbmclapply` than the detected width of the terminal.

I've tested on gnome-terminal, with and without byobu, and with version 1.2.5 and the latest Github version.

Can you reproduce?

**Comment by kvnkuang** [comment]
Hi Scott,

Yes. I can reproduce this bug. It seems like a problem when the ETA is formatted. I'll work on a fix when I get some time.

Thanks,
Kevin

**Comment by scottkosty** [comment]
Thanks for confirming that you can reproduce, Kevin! I appreciate your help on this.
