### ISSUE TITLE
mc.preschedule

### ISSUE THREAD

**Issue by talegari** [kvnkuang/pbmcapply#26]
Hi Kevin,

Thanks for the package!

> Does the design of the package allow exposing `mc.foo` arguments of `parallel::mclapply` like `mc.preschedule`?

Currently, I am forced to use `parallel::mclapply` without a progress bar when `mc.preschedule` is `FALSE`. Would this be a meaningful feature addition?

Regards,
Srikanth

**Comment by kvnkuang** [comment]
Hi Srikanth,

Thanks for reaching out. Currently, these arguments are not passed to `parallel`. I will include them at the next release.

Regards,
Kevin

**Comment by talegari** [comment]
Thanks for a quick reply.
