### ISSUE TITLE
progressBar() error after the 5/11/2018 update

### ISSUE THREAD

**Issue by 33Vito** [kvnkuang/pbmcapply#28]
Hi, 

Firstly, thanks for this great package! I have been using it a lot. 

The recent update has caused the following error in my code (used to work perfectly)

> Error in progressBar(0, length, style = mc.style, substyle = mc.substyle) : 
>   must have max bigger than min. 

I will try to come up with a reproducible example. Meanwhile, let me know if you can think of anything that might contribute to this error. 

Thanks, 
Tony

**Comment by 33Vito** [comment]
Sorry, I figured it out. It is my own bug. This error message is just telling me that the target list is an empty list. 

Though, I would wish the function to support empty list input (i.e. return an empty list just like `mclapply`

Cheers, 
Tony

**Comment by kvnkuang** [comment]
Hi Tony,

Thanks for reaching out. I will implement this and release it with the next update.

Regards,
Kevin
