### ISSUE TITLE
Width calculation problems for short and long durations

### ISSUE THREAD

**Issue by scottkosty** [kvnkuang/pbmcapply#29]
Related to #25. If I use the same use case there with the latest (Github) commit of pbmcapply (`packageVersion()` reports 1.3.0), I get the following output:

![width_problems](https://user-images.githubusercontent.com/1149353/50387795-e10af000-06d2-11e9-8f8a-d75bb2d143d2.png)

If I change `10^7` to `10^2` in the use case, there are still linebreak problems.

Can you reproduce?

**Comment by kvnkuang** [comment]
Hi Scott,

Thanks for reaching out!

Could you please confirm if this problem persists when running the dev version of pbmcapply? You can get the development branch by running the following lines with R:
```{r}
library(devtools)
install_github("kvnkuang/pbmcapply", ref = "dev")
```

Happy Holidays,
Kevin

**Comment by scottkosty** [comment]
Thanks for the quick reply, Kevin!



> Could you please confirm if this problem persists when running the dev version of pbmcapply?

I do confirm that the problem persists while running the dev version.

Happy Holidays,

Scott

**Comment by scottkosty** [comment]
@kvnkuang Thanks for the quick response, and confirming that you can reproduce. Indeed, I'm using `gnome-terminal`. Let me know if I can help by testing anything.

**Comment by kvnkuang** [comment]
It seems like a bug caused by writing more characters than the width of the terminal. I have implemented a better way to draw the progress bar.

Could you please check if the most recent commit in the dev branch fixed the problem? Thanks!

**Comment by scottkosty** [comment]
@kvnkuang Yes, I will check. Thank you!

**Comment by scottkosty** [comment]
@kvnkuang Works great! By the way, just out of curiosity I tested on a very small width. I was sure that I would break something. But `pbmcapply` handles it perfectly (and just shows the percentage without anything else, which is ideal behavior, in my opinion). Well done.

I just sent you an email. Can you confirm here that you received the email, so that I can make sure that I'm talking with the same Kevin?

**Comment by kvnkuang** [comment]
@scottkosty Happy to know it worked. I will push an update to CRAN.

You did catch an edge case that took me a while to cope with (thankfully). One thing that will not work though is if you reduce the width of the windows while tracking the progress will cause some trouble. However, it is because R GUI doesn't update the `width` env in the middle of executing a command.

Yes, I received your email. Thanks again for your support!
