### ISSUE TITLE
`pbmclapply` not capturing dot `(...)` correctly

### ISSUE THREAD

**Issue by thierrygosselin** [kvnkuang/pbmcapply#4]
Hi !

I don't think `pbmclapply` is working properly when using a function with more than 2 arguments. Usually extra arguments are captured in `parallel::mclapply` `...` argument.

might want to use `dots <- pryr::named_dots(...)`

Cheers
Thierry

**Comment by kvnkuang** [comment]
Hi Thierry,

Thanks for your feedback. Could you please show me some code that triggers the bug?

I tried to pass four arguments with and without parameters to both `pbmclapply` and `pbmcmapply` and it seems like they are fine. Here is the code I used for testing:

```
library(pbmcapply)

testMultipleArguments <- function(element, args1, args2, args3, args4) {
  return(paste(sqrt(element) * 10, args1, args2, args3, args4, sep = ", ", collapse = ""))
}

# Tests for pbmclapply
control <- mclapply(1:20, testMultipleArguments, "alice", "bob", 42, "chris")
# Test four arguments
res1 <- pbmclapply(1:20, testMultipleArguments, "alice", "bob", 42, "chris")
# Test four arguments plus parameters
res2 <- pbmclapply(1:20, testMultipleArguments, "alice", "bob", 42, "chris", mc.cores = 4, mc.style = 2)
# Check if the results are the same as control
print(all(identical(control, res1), identical(control, res2)))

# Tests for pbmcmapply
control <- mcmapply(testMultipleArguments, 1:20, MoreArgs = list("alice", "bob", 42, "chris"))
# Test four arguments
res3 <- pbmcmapply(testMultipleArguments, 1:20, MoreArgs = list("alice", "bob", 42, "chris"))
# Test four arguments plus parameters
res4 <- pbmcmapply(testMultipleArguments, 1:20, MoreArgs = list("alice", "bob", 42, "chris"), mc.cores = 4, mc.style = 2)
# Check if the results are the same as control
print(all(identical(control, res3), identical(control, res4)))
```

Could you please run the same code and let me know if you see any error?

Regards,
Kevin

**Comment by thierrygosselin** [comment]
Hi Kevin, thanks for the fast response, 
I think it's a case of specifying globals inside `future::futureCall`.  As the function I use with `mclapply` uses `dplyr` and `random forest`. 
Will try changing it to see if it works
Cheers
Thierry

**Comment by thierrygosselin** [comment]
Hi Kevin, still can figure out how to make it work.

Below my function that's inside the mclapply call:

```
impute_rf_pop <- function(
  pop.list,
  df.split.pop = NULL,
  num.tree = NULL,
  split.number = NULL,
  iteration.rf = NULL,
  ...
){
  sep.pop <- df.split.pop[[pop.list]]
  sep.pop <- dplyr::mutate_all(.tbl = sep.pop, .funs = factor, exclude = NA)
  imputed.dataset <- list()
  imputed.dataset <- randomForestSRC::impute.rfsrc(
    data = data.frame(sep.pop),
    ntree = num.tree,
    nodesize = 1,
    nsplit = split.number,
    nimpute = iteration.rf,
    do.trace = FALSE
  )
  imputed.dataset <- dplyr::mutate_all(.tbl = imputed.dataset, .funs = as.character, exclude = NA)
  
  # message of progress for imputations by population
  message(paste("Completed imputations for pop ", pop.list, sep = ""))
  return(imputed.dataset)
} # End impute_rf_pop
```

That I run like this:

```
input.imp <- pbmcapply::pbmclapply(
        X = pop.list,
        FUN = impute_rf_pop,
        df.split.pop = df.split.pop,
        num.tree = num.tree,
        split.number = split.number,
        iteration.rf = iteration.rf,
        mc.cores = parallel.core
      )
```

We kind of need an extra argument for `futureCall` to work by loading the appropriate package to run the function?

Cheers
thierry

**Comment by kvnkuang** [comment]
Hi Thierry,

Sorry I don't quite understand your question. I see in your function header, there is a dot argument (`...`). However, I see nowhere else it was used nor passed in via `pbmclapply`. Have you tried to remove it and see if the function runs properly?

If that was not your question, could you please be more specific about what went wrong? I see you mentioned `futureCall`. Do you mean the `futureCall()` used in `pbmcapply`?

Thanks,
Kevin

**Comment by kvnkuang** [comment]
Issue closed due to inactivity. Please feel free to update with new information and/or errors.
