### ISSUE TITLE
pbmcapply not showing in Rscript mode

### ISSUE THREAD

**Issue by mrwunderbar666** [kvnkuang/pbmcapply#45]
Awesome package, really love it!

I noticed that when I run a script via `Rscript myscript.r` the progress bar does not appear in the terminal.

Is there an easy way to set that up? Couldn't see anything in the documentation.

Thanks

**Comment by scottkosty** [comment]
`?pbmclapply` gives the following:

```
ignore.interactive: whether the ‘interactive()’ is ignored. If set to
          TRUE, the progress bar will be printed even in a
          non-interactive environment (e.g. called by Rscript). Can be
          set as an option "ignore.interactive".
```

Does that work for you?

**Comment by mrwunderbar666** [comment]
Thanks for your swift reply,

yes that worked, I didn't see that part, Sorry for bothering you

**Comment by scottkosty** [comment]
No bother at all! Thanks for posting back that it works.

**Comment by LuJiansen** [comment]
Thanks @scottkosty, just want to mention that set ignore.interactive = TRUE can also make pbmcapply work in jupyter notebook.
